# Develop
content: content
templates: templates
styles: styles
scripts: scripts
lambdas: lambdas

# Deploy
title: Frozen Pie
github_repo: https://github.com/Facjure/frozen-pie
relative_path: /index.html
