# Develop
content: done
templates: recipe/templates
styles: recipe/styles
lambdas: recipe/lambdas
scripts: lib

## System overrides
default_template: post_plain.mustache

# Deploy
first_page : about.md
title: Frozen Pie
github_repo: https://github.com/Facjure/frozen-pie
recipes_repo: https://github.com/Facjure/frozen-pie-recipes.git
relative_path: /index.html
