# Develop
recipe_root: recipe
content: content
lib: lib

## System overrides
default_template: post.mustache

# Deploy
first_page: page/abstract.md
title: Frozen Pie
github_repo: https://github.com/Facjure/frozen-pie
recipes_repo: https://github.com/Facjure/frozen-pie-recipes.git
