# Develop
# full path, or path relative to pie.py
recipe_root:
content:
routes:
  - controller.js

## System overrides
default_template: post.mustache

# Deploy
first_page: page/about.md
title: Literatte
recipes_repo: https://github.com/Facjure/frozen-pie-recipes.git
